#!/data/data/com.termux/files/usr/bin/sh

# Use neovim for vim if present
if (( $+commands[nvim] )); then
  alias vim="nvim"
  alias view="nvim -R"
  alias vimdiff="nvim -d"
fi

# exa as a replacement for colors
if (( $+commands[exa] )); then
  alias ls='exa --icons'        # replace ls
  alias l='ls -lbF'             # list, size, type
  alias ll='ls -la'             # long list
  alias llm='ll --sort=modified' # long list, sort
  alias la='ls -lbhHigUmuSa'    # all list
  alias lx='ls -lbhHigUmuSa@'   # all + extended list
  alias tree='exa --tree --level=2' # tree view
  alias lS='exa -1'             # one column, just names
fi

# Common aliases
alias h="history"
alias q="exit"
alias CD="cd"
alias up="pkg upgrade"
alias cfg='git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
alias hst="history 1 -1 | cut -c 8- | sort | uniq | fzf | tr -d '\n' | termux-clipboard-set"

# Youtube downloader
alias ytdl="yt-dlp"
alias ytadl="ytdl --embed-thumbnail --sponsorblock-remove default -f 140 -P '/sdcard/Music/'"
alias ytbdl="ytdl -f bestvideo+bestaudio"
# Download the whole dir
alias xdl="wget -r --no-parent --reject 'index.html*'"

# Convert files
alias convert2hevc='ffmpeg -stats_period 10 -i "$1" -c:v libx265 -vtag hvc1 -c:a copy "new-$1"'
# Quick edit
alias zshrc="vim ~/.zshrc"
alias vimrc="vim ~/.vim/vimrc"
alias aliases="vim ~/.config/zsh/aliases"

# Clean up
alias wget="wget --hsts-file='~/.cache/wget-hsts'"

## FUNCTIONS
con2hevc() {
    [ -f "$1" ] && ffmpeg -i "$1" -c:v libx265 -vtag hvc1 -c:a copy "new-$1" || echo "Input file '$1' not found"
}

url_gen() {
    wget -e robots=off --spider --recursive --no-parent --no-directories --reject "index.html*" "$*" 2>&1 | grep -E '^--' | awk '{ print $3 }'
}
# File upload
upload() {
    curl -s https://0x0.st -F "file=@$*" | termux-clipboard-set && termux-toast "Link copied to clipboard"
}
# Exit shortcut
exitshell() { exit }
zle -N exitshell
bindkey 'qq' exitshell
