#!/data/data/com.termux/files/usr/bin/sh

#Editor
if (( $+commands[nvim] )); then
  export EDITOR=nvim
fi

# Clean home
export LESSHISTFILE="${XDG_STATE_HOME}"/lesshst

# Program config
# ani-cli
export ANI_CLI_DOWNLOAD_DIR="/sdcard/Download/"
