#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"



alias h="history"
alias p="pwd -P"
alias s="sudo -s"
alias CD="cd"
alias hc='herbstclient'
alias netprocs="lsof -P -i -n"
alias up="pkg update && pkg upgrade"
alias q="exit"
alias dl="youtube-dl"
alias vim="nvim"
