# Inserts a blank line between shell prompts
add_newline = true

# Put everything in one line
[line_break]
disabled = true

# Replace the "❯" symbol in the prompt
#[character] 
#success_symbol = "[➜]()"

# Disable the package module, hiding it from the prompt completely
#[package]
#disabled = true
